### ISSUE TITLE
Immersive Cables crashes due to differences between AL and AE2

### ISSUE THREAD

**Issue by SanAndreaP** [thiakil/Applied-Energistics-2#100]
Someone tried to use Applied Llamagistics with Immersive Cables, which has AE support, only to be greeted with a crash and report it to IC.

#### Description
Here's the issue I'm referring to: https://github.com/SanAndreasP/ImmersiveCables/issues/9
The problem I see is that AL uses the same mod ID as AE2, thus my mod loads its AE2 module, but it seems there are some discrepancies between the AE2 API and yours:
1. ```appeng/api/util/AECableType``` has a field called ```DENSE_SMART``` in the recent AE2 API, whereas yours has ```DENSE``` (which was the previous AE2 naming from 1.10.2)
2. in the recent AE2 API, you connect 2 grids via ```AEApi.instance().grid().createGridConnection(...)```, whereas in yours you would need to do ```AEApi.instance().createGridConnection(...)```.

#### Environment
- Minecraft Version: 1.12.2
- AE2 Version: rv5-beta-10
- Forge Version: Forge 14.23.1.2582

**Comment by thiakil** [comment]
Indeed, they changed their api post-1.12 release. Mine is still RV3/4 compatible

You will need to retrieve the mod metadata and test the display name if you wish to prevent loading.

**Comment by Waisse** [comment]
What does that mean ? Can we expect future AE addons to work with your fork or not ? Are you able to fix the current issue with Immersive cables ?

**Comment by thiakil** [comment]
Currently they do not because of differences in a number of key APIs. I can indeed make those same changes but it's not easy to pull them in, so I am yet to do so
