### ISSUE TITLE
Suggestion: Creative Booster Card for Wireless Terminal

### ISSUE THREAD

**Issue by Wizardon777** [thiakil/Applied-Energistics-2#101]
Many users in my 1.11.2 pack (Sky Arsenal) have asked me if there's a way to implement a Booster Card for the Wireless Terminal that would work across dimensions.

- Minecraft Version: 1.11.2
- AE2 Version: rv5-beta-10

**Comment by thiakil** [comment]
Quantum entangled dragon egg is what you want ;)

**Comment by Wizardon777** [comment]
Oh! cool! I had no idea... I'll let them know!
