### ISSUE TITLE
Storage buses report only one stack on Thermal Expansion caches

### ISSUE THREAD

**Issue by budgej** [thiakil/Applied-Energistics-2#102]
- Minecraft Version: 1.12.2
- AE2 Version: Llamagistics rv5-beta-10
- Forge Version: 2575

When connected to a cache from Thermal Expansion, storage buses report a maximum of 64 items.  This issue was reported on the [Thermal Expansion issue tracker](https://github.com/CoFH/Feedback/issues/430) but the author said he was not sure how to fix it on his side.

**Comment by thiakil** [comment]
I'm not going to special case every block that does weird shit with its inventory. It's definitely his issue.
