### ISSUE TITLE
PeripheralsPlusOne crash because of AE2 API incompatibility issues 

### ISSUE THREAD

**Issue by JoeSGT** [thiakil/Applied-Energistics-2#105]
#### Description

https://pastebin.com/g5iGBzyU
i have seen there a few AE2 api issues when are you going to update the AE2 api ? because pretty much all AE2 addons are broken with this fork of AE2
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version:  1.12.1-rv5-beta-10.
- Forge Version: 14.23.1.2604

**Comment by thiakil** [comment]
when? who knows
