### ISSUE TITLE
Lag issues with appeng.core.sync.AppEngPacket.processPacket()

### ISSUE THREAD

**Issue by JoeSGT** [thiakil/Applied-Energistics-2#106]
#### Description
It seem my server drop to about 9 to 8 TPS because of this fork 
here is warmroast of the lag, i only have about 5 players online including me when i didn't play just standing there 
![f095c498e22843488cc8655778158393](https://user-images.githubusercontent.com/30296350/36624363-30fbeeb0-18dc-11e8-830f-9d9d6a983b1d.png)
 
#### Environment
- Minecraft Version:  1.12.2
- AE2 Version:  applied-llamagistics-1.12.1-rv5-beta-10
- Forge Version: 1.12.2-14.23.2.2615

**Comment by thiakil** [comment]
Its to do with shift clicking crafting.

**Comment by JoeSGT** [comment]
oh hm are you able to fix it?

**Comment by CyberSpongie** [comment]
I am having the same issue, is there anyway to fix this? or should i remove this fork and not using it?

**Comment by thiakil** [comment]
It is possible to alleviate it a little, its been on my list for some time. But I haven't been working on this mod for a little bit due to lack of motivation. Had major burnout due to the effort required and the fact that it never really caught on, only one major pack picked it up, and they later switched it out anyway.

**Comment by JoeSGT** [comment]
lack of motivation, it's understandable is that i cannot switch out because players are already using ME cells that this forks offers and they are going to lose their items if i switch out
so im stuck with this fork. greatly appreciated if you get around to fix this and others issues

**Comment by JoeSGT** [comment]
@thiakil  Thanks for telling that your not motivated to do work on this fork im going to give my players a heads up warning to move there crap out of the cells that the fork offers, and move to the original on, only reason why i stick with this fork because back in 1.10 it fix sponge and ae2 compatibly but it's fixed now and i will go back to the original ae2 thanks you so much for this mod it was a temp fix for me thanks you so much <3
