### ISSUE TITLE
Stall the entire server for quite some time shift clicking a craft in the terminal.

### ISSUE THREAD

**Issue by ProsperCraft** [thiakil/Applied-Energistics-2#107]
#### Description
On my modpack https://minecraft.curseforge.com/projects/towncraft  I was shift-clicking a recipe for IC2 Raw Carbon Fibre and the entire server locked up for over a minute and everyone was kicked, I captured a nps to be viewed in VisualVM - 
[AE2.zip](https://github.com/thiakil/Applied-Energistics-2/files/1805590/AE2.zip)
Also while it was locked up, I got a stall report- 
[stall-2018-03-12_23.27.45.txt](https://github.com/thiakil/Applied-Energistics-2/files/1805591/stall-2018-03-12_23.27.45.txt)

#### Environment

Multiplayer

spongeforge-1.12.2-2611-7.1.0-BETA-2958
- Minecraft Version: 1.12.2
- AE2 Version: applied-llamagistics-1.12.1-rv5-beta-10
- Forge Version: forge-1.12.2-14.23.2.2625-universal

**Comment by thiakil** [comment]
#106
