### ISSUE TITLE
Crash with AE2 addons

### ISSUE THREAD

**Issue by kave777** [thiakil/Applied-Energistics-2#108]
#### Description

Game crashes during loading 
#### Environment

here is the crash - https://paste.ee/p/W2e64
logs - https://paste.ee/p/8vWyP
I use the latest versions of the addons
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 1.12.2-14.23.4.2703

**Comment by thiakil** [comment]
they are not compatible. use mainline ae2
