### ISSUE TITLE
[1.12] Crafting items in the pattern terminal deletes the item

### ISSUE THREAD

**Issue by Thedrummonger** [thiakil/Applied-Energistics-2#13]
When I put a recipe in the pattern terminal and click the output in an attempt to craft the item it removes the items needed to craft it from the system but does not give the result item. this issue is a little difficult to put into words so enjoy this poorly encoded GIF of the issue in action.
http://imgur.com/a/oq7LO

Applied-llamagistics-1.12-rv5-alpha-2
Forge-14.21.1.2407

**Comment by thiakil** [comment]
fixed for next release
