### ISSUE TITLE
[1.12] Crash upon Server Start

### ISSUE THREAD

**Issue by ImAK9** [thiakil/Applied-Energistics-2#14]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Llamagistics (appliedenergistics2)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
    at java.lang.Class.getDeclaredMethods0(Native Method)

I don't want to rush you or anything but i really need this fixed. Great job with the 1.12 port!

**Comment by thiakil** [comment]
I knew this would happen somewhere xD

**Comment by ImAK9** [comment]
I guess proxies? lol

**Comment by ImAK9** [comment]
Had that problem b4 with my mod bcs of the forge changes

**Comment by ImAK9** [comment]
Any ETA on when you'll do the hotfix? xD

**Comment by thiakil** [comment]
It means some `@SideOnly` is needed (wasn't important pre 1.12 because the function didn't use any client classes).

> Any ETA on when you'll do the hotfix

By sometime tonight my time.

**Comment by ImAK9** [comment]
Awesome! Thank you so much.

**Comment by thiakil** [comment]
https://minecraft.curseforge.com/projects/applied-llamagistics/files/2449949
