### ISSUE TITLE
[1.11.2] Tiny TNT spawns a full-sized primed TNT entity when ignited

### ISSUE THREAD

**Issue by dmarcuse** [thiakil/Applied-Energistics-2#15]
In `rv5-alpha-2`. When igniting a tiny TNT, it spawns a full-sized primed TNT model, but still explodes like a tiny TNT. [Here's a short video displaying the issue.](https://thumbs.gfycat.com/KindlyOrderlyIndochinesetiger-mobile.mp4)

**Comment by thiakil** [comment]
It's a feature! (no not really)

This may have been fixed in dev - a register entity for tiny tnt was missed.

**Comment by thiakil** [comment]
Please test with the latest build.
