### ISSUE TITLE
Grindstone deleting items?

### ISSUE THREAD

**Issue by YourPapy** [thiakil/Applied-Energistics-2#18]
Any item I put in the grindstone gets deleted.

MC version 1.12
Forge Version 14.21.1.2410
AE2 Version rv5-alpha-3

**Comment by tyra314** [comment]
Fixed with 08861bafc8de1fccd4ab92f0a93ff26805300236 - I have just checked - but seems to not be a part of the current release on curse 😿

**Comment by thiakil** [comment]
yep, should be in next release

**Comment by thiakil** [comment]
This has been released now.
