### ISSUE TITLE
Crash with HWYLA

### ISSUE THREAD

**Issue by NielsPilgaard** [thiakil/Applied-Energistics-2#19]
#### Description

I realize this issue is probably caused by HWYLA, but since this mod is in alpha, I figured I'd post it here first. When looking at Energy Cells, both normal and creative, I instantly crash. The expected behaviour would be HWYLA to show details about the Energy Cells.

#### Environment

This was done in Single Player, with a dev build of the Enigmatica 2 modpack.
[crash](https://pastebin.com/mMdAYEMb)

- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-4
- Forge Version: 14.21.1.2412
- HWYLA

**Comment by thiakil** [comment]
Yep, my fault sorry! Working on it, for now at least you can disable the waila integration in config to test other things

**Comment by NielsPilgaard** [comment]
Oh alright, thanks for the quick answer :)

**Comment by thiakil** [comment]
New release should fix this https://github.com/thiakil/Applied-Energistics-2/releases/tag/rv5-1.12-alpha-5

(same file pending on curse)

**Comment by NielsPilgaard** [comment]
It does indeed, thanks!
