### ISSUE TITLE
Search Box Mode for Interface Terminal

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#20]
Add a "Search Box Mode" to the ME Interface Terminal so that people can chose between "Standard Search" and "Auto Search".
As someone who uses Standard Search in the ME Terminals I've always hated that you can't change it in the Interface Terminal.
![2017-07-14_20 51 00](https://user-images.githubusercontent.com/8670392/28226439-74290846-68d6-11e7-8cd9-fe684abdf51d.png)
![2017-07-14_20 51 06](https://user-images.githubusercontent.com/8670392/28226438-74278278-68d6-11e7-9369-692a12080cc1.png)

This also highlights a bug, the background isn't greyed out when opening ME Terminals in 1.12.

**Comment by thiakil** [comment]
Will be in next release (was in a PR that I was gonna grab from 1.10 anyway)
