### ISSUE TITLE
[1.11.2] Grindstone destroys last item in queue

### ISSUE THREAD

**Issue by dmarcuse** [thiakil/Applied-Energistics-2#21]
The grindstone seems to destroy the last item in the grind queue when cranked on `rv5-alpha-2`. For example:

Place 1 ore into grindstone -> crank -> get no dust
Place 2 ore into grindstone -> crank -> get 2 dust
Place 3 ore into grindstone -> crank -> get 4 dust

**Comment by dmarcuse** [comment]
My bad, I didn't realize this had already been fixed, time to update I guess!

**Comment by thiakil** [comment]
Always verify with the last update before making a bug report ;)
