### ISSUE TITLE
[Suggestion] Ability to change Min-Height and Max-Height for Certus Quartz Ore generation

### ISSUE THREAD

**Issue by Volen1** [thiakil/Applied-Energistics-2#22]
After looking through the 1.11.2 version. I am not seeing any option in the Configs to change the Y levels that Certus Quartz Ore spawns at. I also couldn't find it inside of COFH. So would it be possible to add this to the World Generation section of the Config?

**Comment by thiakil** [comment]
It looks like you should be able to add it to the COFH json, as they specify the block in there.

You want `appliedenergistics2:quartz_ore` & `appliedenergistics2:charged_quartz_ore`
