### ISSUE TITLE
JEI recipe transfer failure - Dedicated server

### ISSUE THREAD

**Issue by tyler489** [thiakil/Applied-Energistics-2#24]
#### Description

Using the + in Jei to pull items from the system to the crafting terminal Results in nothing being moved..
On A spongeforge Server.
#### Environment

- Minecraft Version: 1.12
- AE2 Version: applied-llamagistics-1.12-rv5-alpha-5.jar
- Forge Version: 1.12-14.21.1.2407

**Comment by thiakil** [comment]
Can't say I've seen this. Are you sure you have the items?

**Comment by tyler489** [comment]
Yes
i cant craft Sticks and i have 500 wood planks. i cant craft chests using JEI + either

**Comment by thiakil** [comment]
You'll need to show with pictures. And your log.

**Comment by tyler489** [comment]
what kind of log?

**Comment by thiakil** [comment]
client and server (if on server) latest.log

**Comment by tyler489** [comment]
i have 660 copper in the system https://gyazo.com/cb5aae683324a13220c7e8f56197b847 tried to shift click the + in a recipy to convert to a block https://gyazo.com/45405caa47420e7a2e95a23627fe46f9 AND IT doesnt autofill

**Comment by tyler489** [comment]
https://www.dropbox.com/s/fxsc4nkryx41mn0/Serverlatest.log?dl=0
https://www.dropbox.com/s/lxrzatwo4rar9z5/latest.log?dl=0

If you wish to test on the server Download Beyond the New Frontier on the curse launcher. its the only server on the multiplayer list and any of my players can tell you how annoying of a bug it is

**Comment by tyler489** [comment]
Also Another minor thing is when u close the crafting table terminal it doesnt clear the search bar text. would be nice if it did but not a huge issue

**Comment by thiakil** [comment]
Found the problem, will be fixed in next release.

Option to remember search between terminal openings will be a setting too

**Comment by IchigoGames** [comment]
ah i see this is fixed hopeing it comes out before Thursday my modpack update day day

**Comment by thiakil** [comment]
Depends on your timezone I guess. I want to get a couple of small rewrites in before I do a release with all the fixes

**Comment by tyler489** [comment]
Hi ichigo ;)
