### ISSUE TITLE
ME Chest only allows items to be inserted and extracted in stacks of 38 or less.

### ISSUE THREAD

**Issue by laserlemons** [thiakil/Applied-Energistics-2#25]
#### Description
Both shift-clicking and drag/dropping will only do 38 at a time. The screen also flashes when you try to do more than that. This behavior only affects ME Chests and does not extend to normal terminals.

#### Environment
SP and MP

- Minecraft Version:  1.11.2
- AE2 Version:  1.11.2-rv5-alpha-5
- Forge Version:  13.20.1.2386

**Comment by thiakil** [comment]
I will need more details about your setup & modlist. There is nothing in this mod that should cause a screen flash.

**Comment by laserlemons** [comment]
I meant the AE Terminal screen, not the actual computer screen. It's as if it loses power for a split second.

**Comment by thiakil** [comment]
Then your power setup is likely inadequate. I need to see your complete Chest setup

**Comment by laserlemons** [comment]
After further inspection, it looks like this is only a problem when it's connected to other mods' power supplies. It does not happen if you put an Energy Acceptor or ME Controller between the ME Chest and the power supply. Tested with Thermal Expansion and Immersive Engineering creative power supplies.

**Comment by thiakil** [comment]
The ME Chest itself only has a 40AE buffer. Using just the chest can only fill up that buffer for insertion/extraction operations. I'll up it to 64 for the next release
