### ISSUE TITLE
Support Retrogen

### ISSUE THREAD

**Issue by magneticflux-** [thiakil/Applied-Energistics-2#26]
I recently installed this mod, but many of the features require specific worldgen. Team CoFH has a set of feature generators that make this easy to implement.

It looks like [CoFH World](https://github.com/CoFH/CoFHWorld) (extracted from CoFH Lib and only for 1.12) and [CoFH Lib](https://github.com/CoFH/CoFHLib) (for older versions) has an easy way to support world feature retrogen through [this](https://github.com/CoFH/CoFHWorld/blob/master/src/main/java/cofh/cofhworld/feature/IFeatureGenerator.java) interface.

- Minecraft Version: 1.12
- AE2 Version: 1.12-rv5-alpha-5
- Forge Version: 1.12-14.21.1.2415

**Comment by thiakil** [comment]
just add the ores to your COFH json. That interface seems to work a completely different way to normal generation and I'm not gonna have two generators just because of one mod.

Should retrogen become a Forge feature I will implement that.

**Comment by magneticflux-** [comment]
@thiakil While that does generate ores, I won't be able to find new meteors because several thousand blocks away from spawn have already been generated.

I believe that you can wrap an existing WorldGenerator, so you don't need to rewrite existing generators. For instance, the [FeatureGenSurface](https://github.com/CoFH/CoFHWorld/blob/master/src/main/java/cofh/cofhworld/feature/generator/FeatureGenSurface.java) class takes an existing WorldGenerator and applies it on a single square on the surface.

**Comment by thiakil** [comment]
You can use the Metoerite Placer debug tool, or add another dimension to the meteor whitelist.
