### ISSUE TITLE
Cannot make noncrafting autocrafting recipys

### ISSUE THREAD

**Issue by tyler489** [thiakil/Applied-Energistics-2#27]
#### Description

i was going to set up my autocrafting to smelt cobble into stone but there is no way to change from a crafting task to a processing task. the button doesnt do anything seems like the encode pattern button also doesnt do anything
and the clear grids and oredictionary button.. Probably a dedicated server issue

#### Environment

Minecraft Version: 1.12
AE2 Version: applied-llamagistics-1.12-rv5-alpha-5.jar
Forge Version: 1.12-14.21.1.2407

**Comment by thiakil** [comment]
try with the new release and reopen with the error messages if it still occurs

**Comment by tyler489** [comment]
will the new release fix sort by # of items?

**Comment by thiakil** [comment]
Where was that reported?

**Comment by tyler489** [comment]
Nowhere...

**Comment by tyler489** [comment]
#28 ;)

**Comment by thiakil** [comment]
So how do you expect me to know whether something I've not been told about was fixed?

**Comment by tyler489** [comment]
well you did change some code you said. You arnt magic and dont know what will break automaticly?
