### ISSUE TITLE
Sorting does not work on dedicated server.

### ISSUE THREAD

**Issue by metalim** [thiakil/Applied-Energistics-2#28]
#### Description
Sorting item list in terminal (or crafting terminal) works in single player, but not on dedicated server.
Saw that JEI recipe transfer will be fixed in next release. This might be same kind of issue (also worked in SP, but not on server).

#### Environment
- Minecraft Version: 1.12
- AE2 Version: rv5-alpha-5
- Forge Version: 14.21.1.2413
- Modpack: Moderk Skyblock 2 (2.1.2)

**Comment by thiakil** [comment]
Please only report bugs after testing with the latest version.

**Comment by tyler489** [comment]
@thiakil can confirm still an issue in Beta 1
Totally know what version im on and didnt have to edit this.
in addition the only button that works is the one that changes jei search

**Comment by thiakil** [comment]
Alpha 6 is not a thing. Gonna need some logs, as any failures should appear now.

**Comment by tyler489** [comment]
Sort By View Sort Order and Terminal style dont work... let me get you those logs
Beta 1 btw
Client https://www.dropbox.com/s/0wa75fpbh7ety8z/latest.log?dl=0
Server https://www.dropbox.com/s/klcvs6wgatvunvz/Slatest.log?dl=0

**Comment by thiakil** [comment]
Nothing from AL there. Can you show with screenshots exactly what you're seeing? And one of your mod screen showing the version since that's not actually in those logs

**Comment by tyler489** [comment]
http://youtu.be/HMNmMcFAGU0?hd=1
https://minecraft.curseforge.com/projects/beyond-the-new-frontier/files/2451668 Modlist

**Comment by thiakil** [comment]
Uhhh that modpack file says it was updated 4 days ago, and beta-1 of AL was 20 hours ago...

**Comment by tyler489** [comment]
oh im stupid... will update today.

**Comment by metalim** [comment]
Lol. You've updated the mod while I was writing the report.
Thanks.
