### ISSUE TITLE
Issue with SpongeForge

### ISSUE THREAD

**Issue by Peppesto** [thiakil/Applied-Energistics-2#3]
Hello! Could you please resolve an issue with SpongeForge in your builds? 
[Applied-Energistics-2#2482](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2482)

- Minecraft Version: 1.11.2
- AE2 Version: rv5-alpha-1
- Forge Version: 2315

**Comment by thiakil** [comment]
Currently, I'm going to say no. The mod is for Forge, and anything that modifies Forge is contrary to "expected state".

As the coremod doesn't directly load the mentioned class, I don't know how possible it is to fix it anyway, without some serious digging. I guess the IntegrationsType enum loads it somehow, maybe through checking if the mod is loaded; a necessary step.

If the SpongeBootstrap thing makes it load correctly, then that should probably be integrated into Sponge itself.

All that said, the coremod is under investigation for complete removal (at least in my code). So this will become a non-issue.

**Comment by Peppesto** [comment]
No, this problem is not about Sponge. It is about AE. SpongeBootstrap is a workaround. It is [really](https://github.com/Stonebound/Applied-Energistics-2/commit/94ce78d123171d357ab7ff90db35d12003dc36aa) [easy](https://github.com/gabizou/Applied-Energistics-2/commit/da77eeca44a58e7cc96ddbc3c43f057b3ced21b8) to fix. @simon816 made a post that explains the problem if you go to the link I gave and scroll to the last message.
But anyway thank you. You do a really good job.

**Comment by thiakil** [comment]
Weird, I could have sworn I searched the repo for DummyModContainer and came up with nothing (that was the reasoning behind "As the coremod doesn't directly load the mentioned class", which is obviously untrue). Sorry if I came off as dense! lol

Perhaps you'd like to test the experimental branch, where the coremod no longer exists. (saves are not quite compatible between the two however) https://github.com/thiakil/Applied-Energistics-2/tree/experimental-rv5-removecoremod

Depending on how this fork goes I may even remove the whole "have to be able to disable integrations in config" condition, which is the reason the coremod remains in 1.10

**Comment by Peppesto** [comment]
Now it doesn't even work on a pure Forge (version is the same 2315, ae2 is `4f3b9e6`) :(

[fml-server-latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1125470/fml-server-latest.txt)
[latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1125471/latest.txt)

**Comment by Mifesto** [comment]
Look this commit, https://github.com/Stonebound/Applied-Energistics-2/commit/c8d5936c8c0a4286970b802bf49d2bf37dcfa402 

But I ran into a warning: 

> `[00:28:36] [Server thread/WARN] [FML]: Missing English translation for minecraft: minecraft.jar (Не удается найти указанный файл)
java.io.FileNotFoundException: minecraft.jar (Не удается найти указанный файл)
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_131]
        at net.minecraftforge.fml.server.FMLServerHandler.addModAsResource(FMLServerHandler.java:258) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.addModToResourcePack(FMLCommonHandler.java:539) [FMLCommonHandler.class:?]
        at net.minecraftforge.fml.common.LoadController.buildModList(LoadController.java:130) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:338) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:557) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by thiakil** [comment]
The first error is because I forgot to remove the coremod indication from the manifest, no biggie (`[main/ERROR] [FML/]: Coremod AppEngCore: Unable to class load the plugin appeng.coremod.AppEngCore`)

The next one, traced down to `Caused by: java.lang.ClassNotFoundException: appeng.items.tools.powered.powersink.AEBasePoweredItem` is very odd. Perhaps Forge is failing to strip the interface on that class' superclass `RedstoneFlux`

Can you verify AEBasePoweredItem is present inside the jar you compiled?

**Comment by thiakil** [comment]
Post 8f3f1aa525a08763e6fd447e076f7ecd41f2f691 the normal release should be able to be loaded; I've done similar to the PRs mentioned

**Comment by Peppesto** [comment]
> Can you verify AEBasePoweredItem is present inside the jar you compiled?

Yes, it is there.

I have updated to [`dbf21da`](https://github.com/thiakil/Applied-Energistics-2/commit/dbf21dab5566df2cdc467cfc3d09d6452b8b5efd), `AEBasePoweredItem` is inside, still get errors.
[fml-server-latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127460/fml-server-latest.txt)
[latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127461/latest.txt)

[`eb0ee92`](https://github.com/thiakil/Applied-Energistics-2/commit/eb0ee92e0685de10233c42ec589e2ad74f25dd29) is uncompilable unfortuantely.

```
D:\ae2\src\api\java\appeng\api\util\IOrientableBlock.java:50: warning - @param argument "x" is not a parameter name.
D:\ae2\src\api\java\appeng\api\util\IOrientableBlock.java:50: warning - @param argument "y" is not a parameter name.
2 warnings
:javadocJar
:sourceTestJava
:compileTestJava
D:\ae2\build\sources\test\java\appeng\coremod\AppEngCoreTest.java:41: error: cannot find symbol
                assertArrayEquals( EXPECTED_TRANSFORMERS, coreModContainer.getASMTransformerClass() );
                                                                          ^
  symbol:   method getASMTransformerClass()
  location: variable coreModContainer of type AppEngCore
D:\ae2\build\sources\test\java\appeng\coremod\AppEngCoreTest.java:47: error: cannot find symbol
                assertEquals( EXPECTED_CONTAINER_CLASS_NAME, coreModContainer.getModContainerClass() );
                                                                             ^
  symbol:   method getModContainerClass()
  location: variable coreModContainer of type AppEngCore
Note: D:\ae2\build\sources\test\java\appeng\client\render\UVLightmapJsonTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 33.629 secs
```

**Comment by thiakil** [comment]
I did a dumb on the experimental branch - I had the wrong class in the annotation. Though it seemed to work when running through gradle.

Ehh, that's just a test that I forgot to update. Fixed now

**Comment by Peppesto** [comment]
Now it does work with SpongeForge. Thank you!

But I have just found another problem. I copied AE2 to my server alongside other mods and tried to launch it. I got the crash report. Removing mods, I have found conflicting ones:
1. appliedenergistics2-unofficial-rv5-alpha-1
2. buildcraft-7.99.4
3. spongeforge-1.11.2-2315-6.1.0-BETA-2434

If I remove any of them, the server seems to work. I don't know if this problem is connected to AE2 or not. If not please tell me. I will go to another issue tracker (sponge or buildcraft) and tell them about the problem.

[crash-2017-07-06_15.01.34-server.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127667/crash-2017-07-06_15.01.34-server.txt)
[latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127669/latest.txt)
[fml-server-latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127670/fml-server-latest.txt)

**Comment by thiakil** [comment]
Well it's crashing in AE code, but buildcraft must be doing weird things with a fake world... I pushed a commit that should fix it.

You should probably get a message in the log that says `Worlddata was null, server has not started?` now

**Comment by thiakil** [comment]
NB: that's on the main branch, not experimental. Hopefully we won't need experimental

**Comment by Peppesto** [comment]
> NB: that's on the main branch, not experimental. Hopefully we won't need experimental

Yes, I compiled the main branch.

> You should probably get a message in the log that says Worlddata was null, server has not started? now

Yes, I got it close to the end of the log file.
[crash-2017-07-06_15.45.07-server.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127717/crash-2017-07-06_15.45.07-server.txt)
[latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127719/latest.txt)
[fml-server-latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1127720/fml-server-latest.txt)

**Comment by thiakil** [comment]
Yeah Buildcraft seems to be doing weird shit. But shouldn't crash now.

**Comment by Peppesto** [comment]
It has crashed as you see :(

**Comment by Peppesto** [comment]
Should I write to a BC team about it? Or will you try to fix this from your side?

**Comment by thiakil** [comment]
Nope, I failed hard sorry. I added a logger message but forgot to add the `return` line to bail out. Update and recompile. 

I will do some proper testing with BC before the next alpha release

**Comment by Peppesto** [comment]
It does work with all my mods. You're a monster! Thank you!

By the way I found something connected to this issue on a [BC bugtracker](https://github.com/BuildCraft/BuildCraft/issues/3700).

**Comment by thiakil** [comment]
lol Sponge is making assumptions and then crashing in that bug report.
