### ISSUE TITLE
Fluix Crystal not being created with Simple Ore Generation mod Quartz

### ISSUE THREAD

**Issue by dimensionsintime** [thiakil/Applied-Energistics-2#30]
#### Description

When I drop 1 Redstone, 1 Charged Certus Crystal and 1 Simple Ore Gen Quartz (harvested from nether), I do not get any Fluix crystals. I do see the "energy" or "lightning" indicating it's working to create the fluix crystal, but eventually all 3 items disappear with nothing produced after several minutes wait.

Simple Ore Generation is similar to the older mod NetherOres in that it replaces some ores with it's own version, and expands where they spawn, as is the case with their Quartz. I am not sure which mod causes the problem, so I have left reports for both mods. Thanks in advance.

#### Environment

No crash logs produced, no messages in game log indicating any errors.

- Minecraft Version: 1.12
- AE2 Version: 1.12-rv5-beta-1
- Forge Version: 14.21.2419
- Simple Ore Gen Version: 4.07mc1.12

**Comment by thiakil** [comment]
I'm guessing that the Quartz item (the drop/processed from the ore) is for some stupid reason not the vanilla item?

EDIT: also, the lightning is just what the charged certus does on its own

**Comment by dimensionsintime** [comment]
Exactly that. Rohzek replied that it is registered as gemQuartz with the oreDictionary.

**Comment by thiakil** [comment]
I have no idea why you (he) wouldn't just use the standard item, but anyway, I added some oredict support for next release

**Comment by dimensionsintime** [comment]
Rohzek does indicate his quartz is registered as "gemQuartz" in the OD. Thanks for such a quick response, and thanks again for the port. One of my favorite mods.

**Comment by thiakil** [comment]
beta 2 should fix this
