### ISSUE TITLE
Autocrafting stopped working (not a packet issue)

### ISSUE THREAD

**Issue by TheHQBanana** [thiakil/Applied-Energistics-2#31]
#### Description
After placing a security terminal and registering a wireless crafting terminal I am unable to autocraft any items from my normal terminal (clicking on an item that I do not have and thus says "craft" exits the terminal). I can craft from my wireless terminal just fine. I tried registering myself in the security terminal and I can not get the card to go into the security terminal's inventory (the 63 slot part). I do find it interesting that it works on the wireless terminal though.

- Minecraft Version: 
- AE2 Version: applied-llamagistics-1.12-rv5-beta-1.jar (Newest at this time)

**Comment by thiakil** [comment]
Can't reproduce, gonna need more details about your setup

**Comment by TheHQBanana** [comment]
I am going to set up a second system (a smaller version and try to reproduce it). I will do this on the same server.

Also, are you able to put the biometric identifier card in one of the security terminal slots outside of the slot where you can do the settings?

**Comment by thiakil** [comment]
> Also, are you able to put the biometric identifier card in one of the security terminal slots outside of the slot where you can do the settings?

Only if it is a generic unbound card, or not the same game profile as the owner of the security station - the player who placed it.

**Comment by TheHQBanana** [comment]
Ah I see, the server I am playing on has just crashed so I am waiting for it to reboot. I did not know I could not place my own biometric card in the terminal.

**Comment by TheHQBanana** [comment]
hmm... I can't seem to be able to reproduce it.. yet it does keep happening to my main network. This is very interesting. Would you have any idea as to what could be a cause?

Edit. I think i have found the issue:
The fresh new network: https://i.gyazo.com/72545fcbb161d8b70405c34f2dc14f71.png
My main network: https://i.gyazo.com/2921e9b7fae3be5bff0eecdb1d411f8a.png

Both screenshots were taken in a normal ME Terminal. Both systems have a security system with a wireless terminal. Why would 1 terminal show me a button to return to the wireless terminal and the other to go back to the terminal. The one that shows the button to return to the normal terminal (fresh network) works fine with autocrafting.

**Comment by thiakil** [comment]
Not without seeing your security terminal setup and/or server logs

**Comment by TheHQBanana** [comment]
https://i.gyazo.com/977e74ff60fadf3722f1596ca3ff6ba0.png

My setup (the fresh one)

**Comment by thiakil** [comment]
Do you happen to have the wireless terminal in your hand when you get the unexpected wireless terminal button?

**Comment by TheHQBanana** [comment]
It happens even without having it in my hand. I also get it when i click the "crafting status" button in the normal terminal

In the fresh network that also does not occur

**Comment by thiakil** [comment]
break and replace the faulty terminal?

**Comment by TheHQBanana** [comment]
I tried that, I even drained the system of power, i removed the security terminal and wireless access points.. I broke all connections to the core controllers.. nothing solved it

**Comment by TheHQBanana** [comment]
https://i.gyazo.com/bc02a4bb148f8caabbdb6a832a7abf52.png
I have no idea what is going on here.. I disconnected it but it's still getting powered... and this is the only point of connection. As you can see it shows 6 channels going through that smart cable even though it is not connected

Also when I disconnect the security terminal and go to my normal terminal and click the "crafting status" button. It should prompt me with the crafting status and a normal terminal icon in the top right corner. Instead it just exits the terminal outright.

**Comment by thiakil** [comment]
whats at the other end of that cable?

**Comment by thiakil** [comment]
are there any log messages?

**Comment by TheHQBanana** [comment]
I think I figured that one out, it had an energy acceptor as one of the things at the other end (which was only connected to an ME Drive). 3 ME Drives fully stocked and 3 different terminals. That should still not show me the 6 channels on that end of the cable though.... I removed the energy acceptor and they disappeared and the terminals turned off. 

I do not have access to the server logs as I am not the owner. let me ask the owner for any logs/log messages. Any files in particular that would be useful to you?

**Comment by thiakil** [comment]
You client latest.log could offer clues, otherwise the server owner should know what to look for

**Comment by TheHQBanana** [comment]
I find this very interesting.. when i place the crafting terminal on top of the smart cable.. it does what it should do. if i place it facing towards me and i click the "crafitng status" button it wants to go back to the wireless terminal

**Comment by TheHQBanana** [comment]
Only happens when i place it facing south

**Comment by TheHQBanana** [comment]
yep on my fresh system it also bugs when i place it facing south

**Comment by TheHQBanana** [comment]
Please let me know if you are able to reproduce this bug :)

**Comment by TheHQBanana** [comment]
The interesting part is... suddenly it has fixed itself.. it has done this a couple minutes ago as well, but then the bug returns after a couple of minutes

Was able to set up a system with 1 controller, 1 smart cable and 1 terminal. it bugged for about 30 seconds before acting normal. I'm waiting for it to get daytime again... I wouldn't know why, but it seems to be dependant on something

**Comment by TheHQBanana** [comment]
After opening my wireless crafting terminal once, it's back :)

**Comment by TheHQBanana** [comment]
https://i.gyazo.com/aed0a26c3f0b12d9697521ca92ae88ff.png 
this is the small setup i was talking about. It also occurs in this so there's no complicated p2p stuff that's causing it

When I then place the terminal on top of the wire, it works normally.. this is so weird man, sorry


I am only able to reproduce it sporadically -,-
I had it on the south side.. it worked fine, i placed the crafting terminal on the nortside of my wire, i get the wireless terminal icon again. I honestly have no clue hwo to 100% reproduce it as it seems to occur randomly

Edit 3: The south side seems fine and now it's the north side bugging out.. Have you been able to do any confirmations yourself?

**Comment by TheHQBanana** [comment]
ehm.. I am able to see the crafting being done on that fresh network.. but that crafting is done on my main network and the 2 are not even connected. this keeps getting weirder

^ This could have to do with the fact that it is showing me the crafting being done in the wireless terminal network though. (which it shouldnt, because my wireless terminal is not even connected to this network either)

**Comment by TheHQBanana** [comment]
It's getting night again and the south side now broken and the north side works fine. I'm just trying to supply you with as much info as I can (I am a starting mod dev and I know how annoying bugs like these can be)

Edit 1: Daytime has arrived and the south side is still broken...
