### ISSUE TITLE
Search bar clears after returning from JEI recipe view

### ISSUE THREAD

**Issue by tyler489** [thiakil/Applied-Energistics-2#32]
A minor thing but in alpha 5 the search bar in the terminal wouldnt ever clear in Beta 6 if u use JEI recipys the search bar clears as soon as u look at a recipy in JEI
- Minecraft Version: 1.12
- AE2 Version: Beta 1
- Forge Version: 14.21.1.2407

**Comment by thiakil** [comment]
fixed for next release

**Comment by tyler489** [comment]
Also the buttons on the side reset to default when jei recipys are opened
