### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Retepus** [thiakil/Applied-Energistics-2#33]
I have a Problem with an bugging storage disk. Every time this Disc is in the System, the game crashes when i try to open it. ist only this one disks all others are working.
"The game crashed whilst rendering screen
Error: java.lang.IllegalArgumentException: ItemStack must be for default leaves."

#### Environment

- Minecraft Version: 
- AE2 Version: 
- Forge Version:

**Comment by thiakil** [comment]
I need the actual crashlog, not the single line the launcher gives.

**Comment by tyler489** [comment]
also version would be helpful. if u can get the disk out in your inventory and get a player.dat file i suspect i know what mod it is... its probably BOP's tile.BOPLeafAir_1
