### ISSUE TITLE
*Suggestion* Wireless Crafting Terminal

### ISSUE THREAD

**Issue by TheSnowyChickens** [thiakil/Applied-Energistics-2#34]
Hello
It is possible , that you can add a wireless crafting terminal ?
I miss this feature since the 1.7.10 version of AE2. :)

Thx

- Minecraft Version: 1.12
- AE2 Version: applied-llamagistics-1.12-rv5-beta-2.jar
- Forge Version: 14.21.1.2423

**Comment by thiakil** [comment]
The wireless crafting terminal mod was updated to 1.10. This fork may not last longer if they AE2 team manage to actually get a release out

**Comment by thiakil** [comment]
This has been implemented in beta 9
