### ISSUE TITLE
Crash loop with auto crafting

### ISSUE THREAD

**Issue by Xerasin** [thiakil/Applied-Energistics-2#36]
Crash loop when starting a craft using blocking mode

#### Description
Whenever I start a craft with blocking mode on in my situation it causes a crash nearly instantly and the server won't boot up again until I manually delete the crafting storage's tile entity.

#### Environment
Setup: 
![image](https://user-images.githubusercontent.com/1499878/28587680-db6e9da0-712c-11e7-9f00-633a8c0556d3.png)

Crash-log:
https://gist.github.com/868e606dd4779300f56e53ce184e12c9

- Minecraft Version: 1.12
- AE2 Version: 1.12-rv5-beta-2
- Forge Version: 14.21.1.2423

**Comment by budgej** [comment]
Confirming I see the same bug, same AE2 version, same error as in the log above.  Any interface on Blocking mode will crash the server the moment it is put to use.

**Comment by TheLimePixel** [comment]
Yup, multiple people playing my pack have gotten this crash. Just please fix it.

**Comment by budgej** [comment]
Thiakil does this for free.  We are fortunate he chose to tackle this huge project and share it with us.  Have patience.

**Comment by thiakil** [comment]
Also commenting to add that you're experiencing it too is redundant unless it has been asked for.

If you want to be notified about updates, just click the button in the sidebar to subscribe!

**Comment by thiakil** [comment]
Should be fixed in next release
