### ISSUE TITLE
Voided Items

### ISSUE THREAD

**Issue by StenSipma** [thiakil/Applied-Energistics-2#37]
#### Environment

- Minecraft Version: 1.11.2
- AE2 Version: rv5-beta-2
- Forge Version: 13.20.1.2425

First of all, I am not completely sure what the exact problem is, which is causing the problem. I also can't seem to really reproduce the bug completely. My apologies for this, but maybe someone else has also experienced this, and can provide more information.

As the title suggests, some items I put into my ME system, got voided. It both voided some items, when importing items via the 'Import Bus' and when shift clicking items into the 'Crafting Terminal'.
I set up a Drawer Controller (from Storage Drawers version: 1.11.2-4.2.10) with some 'Normal-' and 'Compacting Drawers'. The ME System was connected to the 'Drawer Controller' with a 'Storage Bus'. Some Drawers had void upgrades in them (which i think caused the actual voiding, but not sure). The items which were voided were not able to go into the drawer System, and since I did not setup any other  storage, the items should not go into the ME system. They, however, did and got probably voided in the process.

Edit: This occurred on a Multiplayer Server, on the Preedcraft modpack.

**Comment by thiakil** [comment]
Can you please provide some screenshots of both the system, and the config of the storage bus?

**Comment by StenSipma** [comment]
I changed stuff (basically everything) since the voiding, but I think i only had a storage bus going into a drawer controller, with a priority of 0 (there is a chance it could have been 2000, but im pretty sure it was 0).   I did not change any other config settings for the Storage Bus. 
Again I'm sorry I can't really give exact information.

**Comment by StenSipma** [comment]
Alright had the same problem again on a different version:

Environment:
- Minecraft Version: 1.12
- AE2 Version: rv5-beta-3
- Forge Version: 14.21.1.2428

I was able to reproduce the voiding somewhat reliable, but after a server restart I couldn't seem to be able to reproduce it.

The drawer 'system' consists of a few normal Drawers and a few Compactor Drawers, all of them locked and an item in them. Some drawers are connected with 'trims'.

The ME system consists of a controller, a ME drive, a few terminals, an energy- cell / acceptor and some crafting stuff (probably not important, since I did not have this the last time the voiding happened).

The drawer system and the ME system were connected with a storage bus with a high priority (around 2000). The ME Drive had a priority of 0.

 When I had no cells in the drive, items which shouldn't go into the drawer system (since every drawer is locked and has an item in it), don't go in. This is normal behavior.

When I had cells (with storage space) in the drive, items which I put into the system got voided, if they had no spot in the drawers.

When i had cells (with space) in the drive, and disconnected the compactor drawers. Items went into the right spot (the cell).


As mentioned before this did not happen anymore after a server restart, so it maybe Applied Energistics is not the problem.
I hope these cases can help a bit.

**Comment by thiakil** [comment]
Hmm hard to diagnose if it's not ever present. AL however loops through every possible storage 'cell' (a Storage Bus counts as a cell), and tests if it accepts it. Quite likely the Drawer accepted something which it then voided. Purely conjectural though

**Comment by StenSipma** [comment]
Ye, the problem might originate in another mod. Could be Storage Drawers, but someone also suggested it might be Sponge related?
My reason for submitting it, was just awareness :)

**Comment by thiakil** [comment]
It would not surprise me if it were sponge TBH. If you can reproduce consistently and find it's an AL problem, please reopen.
