### ISSUE TITLE
Missing Texturs with newerst Forge [1.12]

### ISSUE THREAD

**Issue by Fundryi** [thiakil/Applied-Energistics-2#38]
#### Description
Title kinda says it, might be a mod conflict but I don't think so because I just updated Forge to the newest version and the texture where suddenly missed :)

#### Environment
I play/test it on my Singleplayer world.
Missing Textures: https://i.gyazo.com/979f0fc6920faf89389792ddf27c04ff.mp4
My Config: https://gist.github.com/Fundryi/8800a42726abb1861406ac1818dd8d2d
Textures are not missing on forge *.2420 / the same version my public modpack uses.

- Minecraft Version: 1.12
- AE2 Version: Newest
- Forge Version: Newest

**Comment by thiakil** [comment]
Can you reproduce with JUST AL? Gonna need your log too

Also, **don't write newest**

**Comment by Fundryi** [comment]
I can't reproduce the bug with only AL, looks like some kind of Mod incompatibility. But I really don't know why other mods should interfere with your mod, besides Optifine or FoamFix. And I tested them with your mod, all the textures were there. 

Logs:
[fml-client-latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1182389/fml-client-latest.txt)
[fml-junk-earlystartup.txt](https://github.com/thiakil/Applied-Energistics-2/files/1182390/fml-junk-earlystartup.txt)
[latest.txt](https://github.com/thiakil/Applied-Energistics-2/files/1182392/latest.txt)

If you have the Curse/Twitch client, u can try it out yourself I give you my modpack link.
[AL Testing-1.0.zip](https://github.com/thiakil/Applied-Energistics-2/files/1182401/AL.Testing-1.0.zip)

**Comment by thiakil** [comment]
In that case you'll likely need to add mods one by one to see which causes it to fail - you have a lot of model errors showing up, though I don't know if thats a normal thing because of the forge variants tbh.

One thing that does stand out is a NPE in an event handler `PegBeard.DungeonTactics.Handlers.DTEventHandler.randomCount(DTEventHandler.java:1081)` - this occurs a lot.

**Comment by Fundryi** [comment]
I'm really confused right now so I have one problem I know what mod causes it "kinda" but not really. it's freaking weird.
If I disable the mod the Texture errors go away but!
If I try is like this:

Testing Environment
Forge: forge-14.21.1.2426
Minecraft: 1.12
Applied: applied-llamagistics-1.12-rv5-beta-2
BetterWithMods: Better With Mods-1.3.4-1.12
JEI: jei_1.12-4.7.2.77
If I try it like this the textures are there but not in my "big" modpack I really don't know why.

I really don't know why it would but the mod is ["Better With Mods"](https://minecraft.curseforge.com/projects/better-with-mods)

**Comment by thiakil** [comment]
So adding BWM to the test instance (with no Optifine/etc) causes the texture errors?

**Comment by Fundryi** [comment]
https://gyazo.com/80014fc9dcbddc550c59bfd578b69570 Working Great no missing texture or anything but, If I use it in my big Modpack with many other mods, it's still missing textures BUT only if BWM is in it. When I remove it the bug is gone so I really don't know what causes it that's so ayoing.

**Comment by Fundryi** [comment]
With BWM: [GIF](https://i.gyazo.com/c1bacd7602d059d8c02ac9a605d82b04.gif)
Without BWM: [GIF](https://i.gyazo.com/f6250cc0279eaa515360777d69a87c4e.gif)

**Comment by thiakil** [comment]
Please try with Beta 3, a friend alerted me to the presence of a model registry event, which AL now uses. It may solve your issue

**Comment by Fundryi** [comment]
Gonna test it out as soon as it's on Curse :) Thanks for letting me know!

**Comment by Fundryi** [comment]
That fixed it! Thanks for the updated! #Closed

**Comment by thiakil** [comment]
Good to hear. btw, you can just click the close issue button ;)
