### ISSUE TITLE
[1.12] TileSkyCompass is missing a mapping!

### ISSUE THREAD

**Issue by FiveEYZ** [thiakil/Applied-Energistics-2#40]
#### Description
error in console told me to report this

#### Environment
running this modpack https://minecraft.curseforge.com/projects/preedcraft

here is the error
https://gist.github.com/FiveEYZ/d982af8f0d1d8147e4df58ff13494ef5

- Minecraft Version: 
- AE2 Version: applied-llamagistics-1.12-rv5-beta-2
- Forge Version: forge-1.12-14.21.1.2426-universal

**Comment by thiakil** [comment]
Thanks, will fix for next release

**Comment by FiveEYZ** [comment]
sorry for [tagging] the issue, didn't read properly

thx for making this fork <3
