### ISSUE TITLE
Visual bug Wooden Crank

### ISSUE THREAD

**Issue by FiveEYZ** [thiakil/Applied-Energistics-2#43]
#### Description
The crank is not placed correctly (was working on beta-2)

the Quartz Grindstone is still functional
https://i.gyazo.com/097c2d3602ccf499425a3a930915317d.mp4

#### Environment
Running this modpack https://minecraft.curseforge.com/projects/preedcraft
on windows server 2012 r2

- Minecraft Version: 
- AE2 Version: applied-llamagistics-1.12-rv5-beta-3
- Forge Version: forge-1.12-14.21.1.2428-universal

**Comment by thiakil** [comment]
O_o

**Comment by thiakil** [comment]
Did you happen to update forge at the same time?

**Comment by FiveEYZ** [comment]
yes, was also a world wipe when we updated

**Comment by thiakil** [comment]
Quite probably something changed in forge's rendering then I guess; if it's rotating it got registered correctly, but the TESR is just malfunctioning
