### ISSUE TITLE
will this mod continue to be a thing?

### ISSUE THREAD

**Issue by Ushupiuck** [thiakil/Applied-Energistics-2#44]
Hello there! I know this sounds as a weird question. But since the original Applied Energistics 2 has updated, Will Applied Llamagistics continue? Also! Will it be possible in the future to swap between both mods, since this is a fork of it?
As always, thanks for replying, and I hope you guys have a good day! This puzzles me to no end about what to use, now that there's both avaliable @.@

**Comment by thiakil** [comment]
For now, yes. See the new heading on the curse page https://minecraft.curseforge.com/projects/applied-llamagistics#title-1

As for swapping between it *might* work, but also might not.

**Comment by Ushupiuck** [comment]
I just readed it. Thanks! as for the second question..? just curious.

**Comment by thiakil** [comment]
> Will Applied Llamagistics continue? 

> For now, yes.

> Will it be possible in the future to swap

> As for swapping between it might work

Not sure what I didn't answer?

**Comment by Ushupiuck** [comment]
for some reason, the second reply did not appeared to me. I might need to refresh the page... thanks anyways

**Comment by thiakil** [comment]
It was an edit, so yeah thats it :)

**Comment by Ushupiuck** [comment]
off topic, but thanks for bringing this mod to 1.12. I was wondering how to build a sorting + automating system, and now thanks to you, I'm in paradise~
