### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by FiveEYZ** [thiakil/Applied-Energistics-2#47]
#### Description

re-placed some ME Controllers in a network and rebooted, now im stuck in this crash-loop
https://gist.github.com/FiveEYZ/d3fd483efcb02157af78b25ea1ce8064
#### Environment

Windows Server 2012 R2
spongeforge-1.12-2397-7.0.0-BETA-2486

- Minecraft Version: 
- AE2 Version: applied-llamagistics-1.12-rv5-beta-3
- Forge Version: forge-1.12-14.21.1.2443-universal

**Comment by FiveEYZ** [comment]
here is a log from start to stop cause of crash, and it keeps looping

https://gist.github.com/FiveEYZ/b57fc3eb5b74abed600a996e4bb17822

hope it helps :)

**Comment by thiakil** [comment]
Did you use some form of builders/swapping wand?

This cannot happen under normal circumstances; your save file has a TE saved as a controller, but the block at that location is a quantum bridge.

>Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=state, clazz=class appeng.block.networking.BlockController$ControllerBlockState, values=[offline, online, conflicted]} as it does not exist in ExtendedBlockState{block=appliedenergistics2:quantum_link, properties=[formed]}
