### ISSUE TITLE
Quantum Ring Autocrafting doesn't work

### ISSUE THREAD

**Issue by Mr3DAlien** [thiakil/Applied-Energistics-2#48]
When you use a Quantum Ring and making a Exporter with a Crafting Card the Items won't get crafted. Please fix this i need this for my Reactor 

Minecraft Version: 1.11.2
AE2 Version: applied-llamagistics-1.11.2-rv5-beta-4
Forge Version: forge1.11.2-13.20.1.2429

**Comment by thiakil** [comment]
Please be more specific about your setup

**Comment by Mr3DAlien** [comment]
There is not a lot to talk about.. I have simple one Quantum ring on my Controller, and one stands by my reactor [Yes he has power] and when a place an exporter to an chest it pulls the items in the chest. But doesn't autocraft it, when i have a crafting card in it. When i tried that without an Quantum ring, so on my controller it worked... Sorry for my bad english

**Comment by thiakil** [comment]
and you can craft these items manually with a terminal?

**Comment by Mr3DAlien** [comment]
Yes

**Comment by thiakil** [comment]
Works fine for me.
