### ISSUE TITLE
(1.11.2): Lumium blend uncraftable via autocrafting

### ISSUE THREAD

**Issue by ghost** [thiakil/Applied-Energistics-2#49]
I am using the latest of AL available on the latest version of forge.

Steps to reproduce: Simply add this recipe to a pattern, insert it into an interface connected to a molecular assembler and, attempt to auto craft it.

King Lemming is convinced it's on your end. Removing and re-adding the recipe via crafttweaker resolved the issue. It isn't top priority for us but I figured I'd mention it anyways.

https://github.com/CoFH/Feedback/issues/455

**Comment by thiakil** [comment]
> and attempt to auto craft it

What step exactly does it fail?

also **don't fucking write 'latest', it's the least helpful thing ever**

**Comment by ghost** [comment]
Now that I've slept I can take a look at this proper. Thirty six hours of sleep deprivation will do that to do. Insomnia's a bitch.

Here's all the appropriate details:

Version of AL: rv5-beta-4.jar (Recipe was still broken in beta-3)

Version of Forge: 13.20.1.2429

Modlist: https://pastebin.com/zs8r4MAf (manifest pulled from the curse client)

Crafttweaker entry: 
recipes.remove(<thermalfoundation:material:102>);

recipes.addShaped(<thermalfoundation:material:102> * 4,[[<ore:dustTin>,<ore:dustTin>,<ore:dustTin>],[<ore:dustSilver>,<forge:bucketfilled>.withTag({FluidName: "glowstone", Amount: 1000}),null],[null,null,null]]);

Point of failure: http://i.imgur.com/so4g4JJ.png

Crafting CPU: Automatic read Simulation and it was grayed out.  (Usually displayed when a recipe is invalid/there aren't enough cpus/there is not enough internal storage in the cpu).

The start button was also grayed out.

Attempting to reproduce the bug has yielded nothing, leading me to believe that it was the age old 'it just needed a good kick' problem. 

After resetting the AE system (turning it back off and on again), the crafttweaker script is no longer needed. 

This is a fairly common problem with Applied Energistics, especially on larger networks. When it crops up again (and it will), I'll come back to this post.

I wish I could give you something more concrete than "It broke and now it works again". 

Something (wonky leftover code from older versions of AE2?) causes anomalous failure on larger AE networks. In years of playing I've yet to track it down. It only gets worse when you segment the network across P2P buses.

**Comment by thiakil** [comment]
> The start button was also grayed out.

This usually means it cannot find the items in your network.
