### ISSUE TITLE
Search not working with craftable items

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#5]
#### Description
Searching for a craftable item will not show it in the list.
https://youtu.be/4RMVT8ud-t0

I've also noticed it doesn't seem to "refresh" the screen sometimes.

#### Environment
- Minecraft Version: 1.11.2
- AE2 Version: alpha 1
- Forge Version: 2388

**Comment by thiakil** [comment]
Hopefully this is fixed in 267e3b390e33781106c015fe10ff9820387a8ff2

**Comment by thiakil** [comment]
> I've also noticed it doesn't seem to "refresh" the screen sometimes.

As for this part, I'll need more details

**Comment by Xiaminou** [comment]
I'm not sure yet as to what's happening, an example would be when I insert redstone block which are stored in a compacting drawer, it will not refresh the amount of redstone dust that I have until I close and open the terminal GUI.

**Comment by thiakil** [comment]
That _could_ be just how storage drawers work. Or it could be a Storage Bus issue. A test case anyways

**Comment by thiakil** [comment]
The search issue does seem to be fixed btw

**Comment by Xiaminou** [comment]
Well from what I remember of 1.10.2 it did refresh. Like you said, needs further testing.

**Comment by thiakil** [comment]
From what I can tell it probably didn't. But it now correctly updates e.g. Redstone Blocks when you put in / take out Redstone (dust)
