### ISSUE TITLE
[Feature] - An infinite storage disk

### ISSUE THREAD

**Issue by Protheus** [thiakil/Applied-Energistics-2#50]
An infinite disk that is able to hold.. yes an infinite of one item.. just like the one from  Refined Storage

#### Description
You can store an infinite of one item on a disk instead of 63 items per disk

#### Environment
- SP/MP
- Due to being infinite the storage disk can only be placed in a special disk drive, which uses more power than the regular disk.

- Minecraft Version: 1.12

**Comment by thiakil** [comment]
There is a creative storage cell for this exact purpose.
