### ISSUE TITLE
Feature request: Return to previous search after initiating auto-craft

### ISSUE THREAD

**Issue by ghost** [thiakil/Applied-Energistics-2#51]
Currently. after starting a crafting operation at the terminal you will be redirected back to the main page.

Instead of redirecting you back to the main page the terminal should redirect you back to your previous search.

Example:

I search for pistons at the terminal.

I begin an auto-crafting operation for pistons.

The terminal redirects me back to my search for pistons.

This will be especially useful when subsequently crafting small amounts of many different items.

**Comment by thiakil** [comment]
This is a limitation of the minecraft engine. The previous GUI must be closed, and when you are returned to a terminal view, it's a completely new instance. You can enable the setting to remember your search after terminal close and it should remember it (though it will also remember your search if you leave the terminal completely and come back)

**Comment by ghost** [comment]
Cool, didn't even know that was a thing. 

Thanks.
