### ISSUE TITLE
Inscribers autocrafting function broken in last beta

### ISSUE THREAD

**Issue by Tauchy** [thiakil/Applied-Energistics-2#52]
With the last rev 5 beta 4 Inscribers are "broken" if you want to autocraft with them. If you try to Automate Processors no matter how you add the two export busses for redstone and printed silicon the printed silicon will be added to the top and bottom slot in the inscriber, redstone in the middle one. 
Also import bus now sucks out the press from the inscribers, older version of the mod did not do that.

**Comment by thiakil** [comment]
> no matter how you add the two export busses for redstone and printed silicon

This is a flaw in your automation design for not handling a full slot. I'll look at a AL side solution too though.

> Also import bus now sucks out the press from the inscribers

That's a bug though, only the export slot should be extractable.
