### ISSUE TITLE
Cannot load on 1.12.1

### ISSUE THREAD

**Issue by TheLimePixel** [thiakil/Applied-Energistics-2#53]
#### Description
 On MC 1.12.1, when loading the game, the mod bugs out and says: 
![image](https://user-images.githubusercontent.com/25333164/29211056-0693058a-7e97-11e7-828e-c332a0192a47.png)

- Minecraft Version: 1.12.1
- AE2 Version: rv5-bata-4
- Forge Version: 14.22.0.2452

**Comment by Fundryi** [comment]
I would also like to have the Mod updated to 1.12.1 :) please add it!
