### ISSUE TITLE
Terminal Gui's closing randomly

### ISSUE THREAD

**Issue by poboy975** [thiakil/Applied-Energistics-2#54]
Minecraft 1.12
Forge 14.21.1.2443
applied-llamagistics-1.12-rv5-beta-4.jar

Single Player, survival. 

I've tried the crafting, pattern, interface and wireless terminals. All close the gui after 10-20 seconds without fail. In the case of the wireless terminal, it gives the wireless out of range error. I've watched the rest of the terminals, and I cant see the power dieing. Happens too fast to see. I've got a Actually additions powercell providing power by directly touching the energy acceptor. Only config change I've made to this mod is the no channel setting. All mods I have installed are latest available. Other thing that happened, which might be related, is I made 10 quantum storage blocks(kinda deep storage units), I put a storage bus and export bus on each quantum storage block to export my most numerous items, cobble, netherack, coal, etc. After a couple of minutes, the AE network started shutting off as if the power was going out. I removed a cable on the export bus part, reducing the export busses to only 5 instead of 10. Power was fine. The terminal closing was happening before I started the export to the quantum storage units. It's not crashing the game, it's just closing the terminals.

Currently installed mods:
ActuallyAdditions-1.12-r117.jar
ActuallyBaubles-1.12-1.1.jar
allomancy-2.8.2.jar
anima-1.12-0.2.1.jar
applied-llamagistics-1.12-rv5-beta-4.jar
AppliedFluidics-1.12-1.0.0.jar
Architect-MC1.12-1.2.0.6.jar
Aroma1997Core-1.12-1.3.0.0.b103.jar
Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar
astralsorcery-1.12-1.6.1.jar
AutoRegLib-1.3-13.jar
backpacks 1.12 - 3.3.0.jar
Baubles-1.12-1.5.1.jar
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
BetterFps-1.4.6.jar
BiblioCraft[v2.4.3][MC1.12.0].jar
BiomesOPlenty-1.12-7.0.0.2291-universal.jar
Bookshelf-1.12-2.0.0.420.jar
BrandonsCore-1.12-2.3.2.129-universal.jar
Cavern_1.12-v1.10.0.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12-2.8.7.jar
Chisel-MC1.12-0.0.13.15.jar
CodeChickenLib-1.12-3.1.1.288-universal.jar
CoFHCore-1.12-4.3.3.11-universal.jar
CoFHWorld-1.12-1.0.0.6-universal.jar
com.pengu.compiler.jar
CommonCapabilities-1.12-1.3.4.jar
Craftable Saddles[1.12]-1.3.jar
CTM-MC1.12-0.2.1.5.jar
CyclopsCore-1.12-0.10.12.jar
DarkUtils-1.12-1.6.167.jar
deepresonance-1.12-1.4.9.jar
Draconic-Evolution-1.12-2.3.3.261-universal.jar
DungeonTactics-1.12-0.12.8.jar
ElecCore-1.12-1.8.429.jar
ElevatorMod-1.12-1.3.4.jar
embers-0.221.jar
EnderCompass-1.12-1.2.6.1.jar
endercrop-1.12-1.3.4.jar
enderutilities-1.12.0-0.7.3.jar
extrautils2-1.12-1.5.1.jar
ExtremeReactors-1.12-0.4.5.34.jar
filenames.txt
Flesh2Leather [1.12].jar
Forgelin-1.5.1.jar
FTBLib-4.0.5.jar
FTBUtilities-4.0.3.jar
gravestone-1.8.4.jar
HammerCore-1.12-1.9.4.0.jar
Hwyla-1.8.20-B35_1.12.jar
IntegratedDynamics-1.12-0.8.4.jar
IntegratedTunnels-1.12-1.2.5.jar
ironchest-1.12-7.0.31.818.jar
itemscroller-1.12.0-0.11.0.jar
jei_1.12-4.7.5.85.jar
journeymap-1.12-5.4.9.jar
JustEnoughResources-1.12-0.8.3.23.jar
limelib-1.12-1.7.4.jar
malisiscore-1.12-6.0.4.jar
malisisdoors-1.12-7.0.4.jar
Mantle-1.12-1.3.1.18.jar
mcjtylib-1.12-2.4.4.jar
MCMultiPart-2.2.2.jar
minecolonies-universal-1.12-0.8.3238.jar
MobGrindingUtils-0.3.2.jar
MouseTweaks-2.8-mc1.12.jar
notenoughwands-1.12-1.5.9.jar
PackingTape-1.12.0-0.7.4.jar
Psi-r1.1-52.jar
QuantumStorage-1.12-4.4.0.jar
Quark-r1.2-104.jar
QuickLeafDecay-MC1.12-1.2.3.jar
RebornCore-1.12-3.2.5.88-universal.jar
RebornStorage-1.12-2.0.1.6.jar
RecipeManipulator-1.12-0.3.0.11.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
refinedstorage-1.5.16.jar
refinedstorageaddons-0.1.1.jar
ReinforcedTools-2.1.1.jar
reptilemod-1.12-3.8.2-73.jar
rftools-1.12-6.12.jar
rftoolsctrl-1.12-1.6.8.jar
rftoolsdim-1.12-5.04.jar
ShadowMC-1.12-3.8.0.jar
SilentLib-1.12-2.2.7-85.jar
SilentsGems-1.12-2.4.5-215.jar
SoulShards-TOW-1.12-2.7.3-52.jar
StevesCarts-1.12-2.4.6.36.jar
StorageDrawers-1.12-5.2.9.jar
TechReborn-1.12-2.6.10.170-universal.jar
Tesla-1.12-1.0.60.jar
The Beneath-1.12-1.2.0.jar
theoneprobe-1.12-1.4.17.jar
ThermalDynamics-1.12-2.3.3.10-universal.jar
ThermalExpansion-1.12-5.3.3.15-universal.jar
ThermalFoundation-1.12-2.3.3.10-universal.jar
transprot-1.12-1.5.0.jar
UnderwaterUtilities-1.12-1.3.2.jar
VanillaTeleporter-1.12-1.6.3-beta4.jar
VeinMiner-1.12-0.38.1.639+134fb1e.jar
WailaHarvestability-mc1.12-1.1.11.jar
Wawla-1.12-2.5.239.jar
Waystones_1.12.1-4.0.13.jar
YukariLib-1.12-1.3.0.jar
zerocore-1.12-0.1.0.9.jar

**Comment by thiakil** [comment]
Definitely sounds like a power issue (though I would expect the terminals to grey-out rather than close). Try adding an AE power cell or two to increase the network's buffer.

Otherwise you'll need to find the minimal setup (and modlist) that triggers it.

You latest.log would help too.

**Comment by poboy975** [comment]
Ok, I'll add a couple of ae power cells and test that out first. Here is my latest log file.
[2017-08-11-3.log.gz](https://github.com/thiakil/Applied-Energistics-2/files/1219571/2017-08-11-3.log.gz)

**Comment by poboy975** [comment]
Ok, that seems to have been the issue, just not enough of a power buffer. I added 2 dense energy cells, and it's not closed the gui on me once since then.

**Comment by thiakil** [comment]
It still shouldn't be closing the GUI... It usually only shows disconnected slots - place a terminal on the ground without connecting to a network and open it, that view is what I mean
