### ISSUE TITLE
Inscriber Automatic Insertion All Insert In Top Slot

### ISSUE THREAD

**Issue by StenSipma** [thiakil/Applied-Energistics-2#55]
#### Description

As the title suggests, inserting an item in the Inscriber puts it into the upper slot first. It does not matter from which side you input the item. I tried using xnet Advanced Connectors and Thermal Expansion Itemducts, both with the same result. For the items I tried the Printed Silicon and redstone, since those are items you don't want to go into the top slot.
Inserting from most sides (Top, Left, Right, Front, Back, Bottom) all result in the same thing (top slot).

I noticed this happening since Applied Fluidicts was added, so the problem might originate there.

Reproducing is pretty simple, since it happens every time when one tries to insert an item.

#### Environment

- Minecraft Version: 1.12
- AE2 Version: rv5-beta-5
- Forge Version: 14.22.0.2452
- Applied Fluidicts: rv5-beta-5
- Multiplayer

**Comment by thiakil** [comment]
The top and bottom slots are swapable, doesn't have to be the exact same as the recipe.

Inserting from any side is also intended, I removed the sidedness.

The item handler in the latest release should be handling slots correctly - and my tests with an export bus showed that it does. So the remaining possibility is that those mods are using the old `IInventory` methods (and that would not surprise me in the least with TD ducts given Lemming's views on capabilities) and somehow not checking validity (which is surprising).

Will need some investigation.

**Comment by thiakil** [comment]
Just make sure you are indeed on beta 5, as 4 was indeed borked

**Comment by StenSipma** [comment]
I copied the versions from the in-game mod options thing, so im pretty sure it is the correct version.

**Comment by thiakil** [comment]
No worries, just making sure

**Comment by StenSipma** [comment]
I tried to do a setup with exporters as well, but that also caused problems. I had an exporter on the back of the inscriber exporting redstone. Redstone also went into the top slot first, and then the middle slot. It did not go into the bottom slot.

**Comment by StenSipma** [comment]
After some further trying, it seems there are some other weird things happening. 
1. I am able to insert redstone by hand, but not when there is already a printed engineering circuit (diamond) in the inscriber.
2. The exporter exports the redstone correctly (in the middle slot), when there is a circuit in the bottom or top slot. If you have nothing in the top slot, and a circuit in the bottom slot, it does not export redstone into the top slot. However, when you remove the circuits from the bottom slot, redstone does export in the top slot.

**Comment by StenSipma** [comment]
I tested the problems mentioned above in creative, and the same thing happens there as well.

There seems to be another thing with inserting (acceleration) cards into the inscriber. (I can make a separate Issue for this, but it's kinda related to the inscriber).
I have made some screenshots, with all of them, I started out with an empty inscriber. I made the screenshot directly after shift clicking the circuits which can be seen in the screenshot (inside the inscriber, not the inventory) and the acceleration cards.

https://gyazo.com/d1cf3ad38d6294d4ac4ef7ecd9765ee8
https://gyazo.com/79203d0a7114e3440d2f1631b2166344
https://gyazo.com/47690eb3c740f1b9369e4eea403c3fa8
https://gyazo.com/c972a5afc24065cf84a78c8e2867a5bb
https://gyazo.com/7361224e46b0ce4d012bc2f2b5f04436
https://gyazo.com/3a68e4a1448b7edae7c285dd5f87797e

https://gyazo.com/4c550643a3f8eb50ae4dd62a8c66da4b
https://gyazo.com/b5a106ea4dc0f1fd631a6fb1d06fc0b8
https://gyazo.com/05157bcc5057c866d93533598fb7b6d7
https://gyazo.com/87f8cf8f7528ff4c8792faefe8a20746
