### ISSUE TITLE
Tesselating block model

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [thiakil/Applied-Energistics-2#56]
crash when loading into the world/ tping to an area where there is a drive.

#### Description
Same thing above, crash happens with Drives are placed and you teleport to an area where those may be. this can also happen as you login to the game.
#### Environment
This is in Multiplayer, 1.12.1 on the Modern Skyblock 2 Official server

https://pastebin.com/PR40aVGf

- Minecraft Version: 1.12.1
- AE2 Version: 
appliedenergistics2-core{rv5-beta-5}
- Forge Version: 
forge-1.12.1-14.22.0.2452

**Comment by thiakil** [comment]
This should not be possible, unless some other mod is messing with the BlockState given or rendering in general. Please try to remove mods until it stops happening.

**Comment by TheLimePixel** [comment]
I looked in the crash log again and it mentions codechickencore rendering. Could CodeChickenCore be the cause maybe?

**Comment by thiakil** [comment]
Any mod messing with the rendering pipeline *could* cause it, but CodeChicken is unlikely (though only by general reputation). 3.1.1.288 doesnt on my instance (different pack & Forge).

It looks like it might be possible to happen if the TileEntity doesn't exist at that location. Though again, that's not normal. Do you have any kind of builder's wands in the pack?

**Comment by thiakil** [comment]
I've added some logging in 44534db100036e369dc154de5b4e779180310bec if you wish to compile and test.

**Comment by cjm721** [comment]
Compiled and loaded up the world causing the issues.
```
[00:18:28] [Chunk Batcher 1/ERROR] [AE2:C]: BlockState does not contain DriveSlotsState. THIS IS NOT NORMAL. BlockState supplied is of type {}.
[00:18:28] [Chunk Batcher 1/ERROR] [AE2:C]: appliedenergistics2:drive
```

**Comment by thiakil** [comment]
Damn, forgot this project uses the other formatting log.

on https://github.com/thiakil/Applied-Energistics-2/blob/44534db100036e369dc154de5b4e779180310bec/src/main/java/appeng/client/render/model/DriveBakedModel.java#L99

Change `{}` to `%s` and it should give us the class name.

**Comment by cjm721** [comment]
```
[00:44:39] [Chunk Batcher 3/ERROR] [AE2:C]: BlockState does not contain DriveSlotsState. THIS IS NOT NORMAL. BlockState supplied is of type {pl.asie.foamfix.common.FoamyExtendedBlockState}.
[00:44:39] [Chunk Batcher 3/ERROR] [AE2:C]: appliedenergistics2:drive
```

Going to try without foamfix now.

**Comment by cjm721** [comment]
Without foamfix does not crash now. Still having a ton of rendering errors, but don't know whats from the original crashes or what.

**Comment by thiakil** [comment]
> Still having a ton of rendering errors

From AL, or something in general?

**Comment by cjm721** [comment]
And re-logged and crashed again. Throwing back on the dev version.

**Comment by cjm721** [comment]
```
[01:10:23] [Chunk Batcher 8/ERROR] [AE2:C]: BlockState does not contain DriveSlotsState. THIS IS NOT NORMAL. BlockState supplied is of type {net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation}.
[01:10:23] [Chunk Batcher 8/ERROR] [AE2:C]: appliedenergistics2:drive

```
This is without foamfix.

**Comment by thiakil** [comment]
ok. Is it actually crashing, or just logging that?

**Comment by cjm721** [comment]
Crashing on non-custom version. Dev version just logging.

**Comment by thiakil** [comment]
- Have you any idea which drive it is specifically? 
- Can you open its GUI/etc? 
- Does it render cells after a bit or is it just spamming the log?

**Comment by EPIICTHUNDERCAT** [comment]
thanks Cj for troubleshooting this o/ best guy for the job

**Comment by cjm721** [comment]
Know which drive it is exactly as there is only one (also when crashed it says which one). 
I am able to open the GUI
The cells do render, while spamming.

**Comment by thiakil** [comment]
Something has to be messing with the rendering code then. It's probably calling the render method with a normal blockstate, rather than one returned by `getExtendedState` like it's supposed to.

**Comment by thiakil** [comment]
The latest update I released includes this logging and some logging in the `getExtendedState` method if it can't grab the TileEntity. If the TE message *doesnt* appear at all then my assumption above is more likely

**Comment by cjm721** [comment]
```
[11:16:10] [Chunk Batcher 8/WARN] [AE2:C]: Could not get TE for drive at MutableBlockPos{x=-6985, y=84, z=7011}, world is net.minecraft.world.ChunkCache
[11:16:10] [Chunk Batcher 8/ERROR] [AE2:C]: BlockState does not contain DriveSlotsState. THIS IS NOT NORMAL. BlockState supplied is of type net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.
[11:16:10] [Chunk Batcher 8/ERROR] [AE2:C]: appliedenergistics2:drive
```

**Comment by thiakil** [comment]
Hmm as I thought, something is trying to render it from a ChunkCache where the TE doesnt exist. There's not a huge amount I can do there, especially if it's spamming while succeeding to render it elsewhere...
