### ISSUE TITLE
(Shift-)Right clicking into air with Network Tool crashes client

### ISSUE THREAD

**Issue by Discomanco** [thiakil/Applied-Energistics-2#58]
#### Description

If you (shift-)right click into the air with the Network Tool, the client crashes.
This only applies to the Network Tool, and not the (Certus) Quartz Wrench.

Right clicking on a normal block opens up its interface (as expected)
Right clicking on an AL block opens the Overview (as expected)
Right clicking in air crashes the client
Shift-right clicking on a normal block does nothing (as expected)
Shift-right clicking an AL part removes the AL part (as expected)
Shift-right clicking in air crashes the client

#### Environment

Enigmatica 2 modpack, SMP.

Edit: Completely forgot crash-log *doh* https://pastebin.com/z4bhL4Jm

- Minecraft Version: 1.12
- AL2* Version: rv5-beta-6
- Forge Version: 2443

**Comment by thiakil** [comment]
I'll double check that I'm triggering the event properly, but that's crashing in Vazkii's code.

```
 at vazkii.quark.decoration.feature.FlatItemFrames.onPlayerInteract(FlatItemFrames.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_544_FlatItemFrames_onPlayerInteract_RightClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```

**Comment by thiakil** [comment]
Ok yeah, the event probably gets created with an air block (or null side) referenced, and I'm just passing in the info I get (probably from other functions in my class). Quark appears to be assuming that the `facing` parameter is always valid, when it is in fact marked as `@Nullable`

Next version won't trigger it for air or null side, but quark code is indeed broken.
