### ISSUE TITLE
AL blocks getting removed

### ISSUE THREAD

**Issue by FiveEYZ** [thiakil/Applied-Energistics-2#59]
#### Description
wanted to make u aware of this issue and tell that its also happening with AL
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3013

All AL blocks in random chunks are getting randomly removed when the chunks gets loaded
one example that happen on our server: 
- A player had a system running and he decide to go out exploring, after a while when he teleport back he noticed his system is no longer running. Turned out a random chunk in his base that had AL blocks,  no longer had any.

its also happening on server restarts like the other issue.

it all started with this https://github.com/MinecraftForge/MinecraftForge/pull/4281
#### Environment
Windows Server 2012 R2
spongeforge-1.12.1-2444-7.0.0-BETA-2566

Minecraft Version:
- AE2 Version: applied-llamagistics-1.12-rv5-beta-5
- Forge Version: forge-1.12.1-14.22.0.2459-universal

**Comment by thiakil** [comment]
I was aware of the issue indeed. The narrowing of it to a Forge PR is new since I last looked, but there still does not seem to be enough info to narrow down the specific cause. 

What we need is server logs from right after it happens. The only log posted in the AE2 issue appears to stop right after the server starts up.

**Comment by FiveEYZ** [comment]
http://paste.ubuntu.com/25374165/ (the error repeats quite a lot, makes the log 82470 lines long)
I restart the server every 6 hour and this log is everything in between 1 of those restarts.

it all starts after line 1288, when a player who have a AE2 system teleported home after he logged in

**Comment by thiakil** [comment]
Many or all of those are (once again) crashing in sponge code. 

I've never understood the desire to freeze state when unloading, when all it ever seems to cause is problems.

**Comment by thiakil** [comment]
You need to report those to sponge. It's not actually crashing, Sponge is just being whiny.

If it can be reproduced without Sponge there may be something that can be done.

**Comment by Discomanco** [comment]
We just upgraded to 1.12.1, and to AL rv5-beta-7 on our Forge server, and this started happening (not affecting the whole server, but just some areas).
The server console doesn't say anything though

**Comment by cjm721** [comment]
Same issue as Lukas45 and we are not using sponge.

**Comment by thiakil** [comment]
Please try to provide some useful information like relevant logs or reproduction steps.

**Comment by Discomanco** [comment]
Well, thats the issue...
No logs are generated, the server console doesn't say anything at all (SMP)
For reproduction, it only affects certain chunks, and there doesn't seem to be any telling what chunks it is.
Another member on our server had his NBT Data wiped in every block in his main AE Chunk (incl ME Drives) - which did include other machines.
I have 1 Thermal energy cell being wiped of NBT Data. Just that 1, out of 3 in the same chunk, same subchunk too.
So I don't know if this is an issue with Forge, maybe 1.12.1, or something completely different

I know this makes it extremely hard to pinpoint, but we don't get a lot of info either.

**Comment by cjm721** [comment]
Been happening all of 1.12 no errors.

**Comment by thiakil** [comment]
So far no one has even presented a strong case it's even caused by AL/AE - everywhere I see mentions of other mods in the same chunk.

I also know with 99% certainty that TE cells losing data *has nothing to do with AL/AE* as I have seen it happen in a chunk without any AL blocks. So quite frankly if you have any TE blocks in a chunk this happens in I'm going to consider it not my problem.

**Comment by tyler489** [comment]
Its a forge issue
