### ISSUE TITLE
Some patterns don't show the crafted item's icon when holding shift

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#6]
#### Description
Some patterns don't show the crafted item's icon when holding shift
![2017-07-06_00 41 45](https://user-images.githubusercontent.com/8670392/27888104-914588a8-61e4-11e7-98c7-50a401608668.png)

#### Environment

- Minecraft Version: 1.11.2
- AE2 Version: alpha 1
- Forge Version: 2388

**Comment by thiakil** [comment]
Could you please list which ones don't work? I can see ME Interface is one; does it happen with all other AE blocks?

**Comment by thiakil** [comment]
Seems fixed after the models refactor/update I did today, so should be fixed in the next alpha.
