### ISSUE TITLE
Cables, Terminals and Buses disappearing

### ISSUE THREAD

**Issue by NielsPilgaard** [thiakil/Applied-Energistics-2#60]
#### Description

When a chunk with Applied Llamagistics cables, buses or terminals is unloaded and then loaded again, the blocks will disappear. It also removes drives from ME Drives, and rotates them. It appears they get reset to a default position?
The issue doesn't happen with all chunks, and it doesn't occur every time a chunk is unloaded and then loaded.
It's worth noting, that when it happens, Thermal Expansion machinery has all upgrades and settings reset, but they don't cause the issue without Applied Llamagistics blocks in the same chunk.

#### Environment

The issue only occurs on servers AFAIK.
The issue was made with the Enigmatica 2 modpack, version 1.05.
[Forced crash](https://gist.github.com/NillerMedDild/300a5ae2eb886c29ffb529f2a4a2ae57)

- Minecraft Version: 1.12.1
- AE2 Version: applied-llamagistics-1.12-rv5-beta-7
- Forge Version: 1.12.1-14.22.0.2462

**Comment by NielsPilgaard** [comment]
It seems to be related to this issue: 
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3013

**Comment by NillerMedDild** [comment]
May I ask why this issue was closed?

**Comment by NielsPilgaard** [comment]
Found the other issue on the git relating to this, my bad.
