### ISSUE TITLE
Issues with power

### ISSUE THREAD

**Issue by tyler489** [thiakil/Applied-Energistics-2#63]
- Minecraft Version: 1.12.1
- AE2 Version: let me look 
- Forge Version: Forge is at version 14.22.0.2460
When moving 320 rf/t through harderd fluxducts directly to a controller the buffer of power drains till it is empty. Using the same setub but with an energy accepter attached to a controler it will gain power.

**Comment by thiakil** [comment]
What is the power usage of your network?

**Comment by andr9528** [comment]
I also seem to have some form of power issue, i have returned twice to my base, with it completely drained (i have a 18 mil storage capacity), despite only being away for 5-10 min both times and having a positive gain at all times of the minecraft day. My power is inserted into a energy acceptor directly from a Advanced Powercell (no fluxduct). my system uses 347 RF/t.

**Comment by thiakil** [comment]
Please post a screenshot of the network tool gui (right clicked on to a networked block)

**Comment by andr9528** [comment]
![2017-09-16_16 02 46](https://user-images.githubusercontent.com/21788044/30512846-95571c3e-9af8-11e7-8ea6-4e6e1c1d9885.png)

It happened again like 5 min ago, this time i were gone for a longer time (hunting wither skeletons), but still my system should be able to keep up.

As generators i have:
8 * Magmatic generators from extra utilities, 4 genarating 200 rf/t each & 4 genarating 80 rf/t each , which i just upped to 120 rf/t, after this third power leakage
6 Culinary generators from extra utilities genarating 48 rf/t each
A Tier 1 Solar Array from Environmental tech (generating 549 rf/t in daytime)

As Machines/systems using power i have:
A Redstone Furnace that makes Rice Bread for the culinary generator which runs occasionally (80 rf/t when it runs)
A Farmer from actually additions farming rice seeds (unsure how much it uses)
A Tier 1 Void Ore Miner from Environmental tech (estimated it earlier to use around 600-700 rf/t)
The AE system, which power use can be seen on the picture

Out of all the things only the AE system has a constants fluctuating power use (0,02 rf/t fluctuation right now, when looking with network tool)

**Comment by thiakil** [comment]
You need to have AE energy cells on the network to increase the buffer.
