### ISSUE TITLE
Name Press Item duplication

### ISSUE THREAD

**Issue by hugeblank** [thiakil/Applied-Energistics-2#66]
#### Description
The issue occurs when putting any item in an inscriber with a name press. It duplicates the item without any error, 100% of the time.

#### Environment
This issue occurs on my server Sonar X. Multiple users have tested this and confirmed that it occurs. [Here](https://kaos-network.com/servers/sonarx) is the link to the server pack information, and installer. Please consider testing it with the modpack in Single Player, here are the steps to recreate:
1. Get a name press using the quartz cutting knife and naming it whatever you want.
2. put it into an inscriber (powered of course)
3. put 2 items of your choice into the inscriber
4. watch.
As you will see it inscribes the first plank, but outputs 2, and then inscribes the second one normally.

- Minecraft Version: 1.11.2
- AE2 Version: rv5-beta-7
- Forge Version: 13.20.1.2393

**Comment by osmarks** [comment]
It appears to be accidentally outputting the entire stack named while using just one item from the stack, instead of taking one item and outputting a named version.

**Comment by Keanu73** [comment]
I can confirm this as well.
