### ISSUE TITLE
JEI and Pattern Terminal

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#7]
#### Description
Using JEI's "+" to put a recipe in the pattern terminal actually uses the items.
https://youtu.be/0bBIVA2M5y0

as a bonus: note that when I click the output to attempt to craft the item, if you don't have what's necessary to craft it it will remove the output until you close and re-open the terminal.
#### Environment
- Minecraft Version: 1.11.2
- AE2 Version: alpha 1
- Forge Version: 2388

**Comment by thiakil** [comment]
So to be clear, in the video:
1. You have covered cables (and recipe) in your system
2. You hover covered cables and use jei's 'uses' key (?)
3. Click the +
4. Covered cables in the system disappear (?)

> as a bonus: note that when I click the output to attempt to craft the item, if you don't have what's necessary to craft it it will remove the output until you close and re-open the terminal.

Honestly I didn't know you could actually craft with the Pattern Terminal. WIll investigate what's bugging out there.
If you don't have the items available, how does the JEI button fill the pattern matrix? That's not supposed to happen.

**Comment by Xiaminou** [comment]
Yes, that is what I did.
You can actually craft with the pattern terminal as long as you have the items you can click the output to craft it.
the JEI button filled the pattern matrix because I had the items, but when it filled it it consumed those items, which is the bug I am reporting, using the "+" button should put the items in the matrix but not consume them.

**Comment by thiakil** [comment]
I found the dodgy code. Fixed for next release.

Clicking the output to craft now works correctly too
