### ISSUE TITLE
Sticky Search

### ISSUE THREAD

**Issue by ZeroInputCtrl** [thiakil/Applied-Energistics-2#70]
When using a terminal, whenever you change to the processing screen or you tell it to craft an item the search clears. It would be great if the search stayed put until actually leaving the machine. Maybe even have an option on the side to keep it persisted even when closing it out as well?

**Comment by thiakil** [comment]
There is indeed a config option to do that.

**Comment by ZeroInputCtrl** [comment]
I didn't see that, it works thanks!
