### ISSUE TITLE
JEI Pattern Transfer

### ISSUE THREAD

**Issue by ZeroInputCtrl** [thiakil/Applied-Energistics-2#71]
I would be great if the pattern transfer would also work on processing patterns as well. Refined storage has this options and works quite well with JEI on adding any pattern for machines.

**Comment by thiakil** [comment]
It has indeed been thought about

**Comment by thiakil** [comment]
implemented

**Comment by ZeroInputCtrl** [comment]
:D cant wait til the next version comes out!
