### ISSUE TITLE
Terminal scaling

### ISSUE THREAD

**Issue by ZeroInputCtrl** [thiakil/Applied-Energistics-2#72]
Is it possible to set the scaling of the tall terminal mode, in JEI there is a button that the search box covers so every time i click on the search box it also clicks that button.

**Comment by thiakil** [comment]
No, it's either tall or not. You might want to switch the JEI search box to be on the right rather than centred.

**Comment by ZeroInputCtrl** [comment]
Your search box covers the JEI Mods button dropdown. But even if i click on the search it also registers the click on the mods button.

**Comment by thiakil** [comment]
could you post a screenshot? JEI only has a search box and a button beside that for config as far as im aware.

**Comment by ZeroInputCtrl** [comment]
Normal Inventory: http://prntscr.com/gja369
Mod button pressed when trying to search terminal: http://prntscr.com/gja3bo

**Comment by thiakil** [comment]
That ain't JEI, perhaps NEI. The Terminal GUI has remained unchanged for quite some time now, you should probably see if there's an option to move the mods button.

**Comment by ZeroInputCtrl** [comment]
This is jei ![image](https://user-images.githubusercontent.com/2280933/30249181-785e5942-9604-11e7-8d61-268b7feadde2.png) the mod button has been there for as long as I can remember. There is no way to move it and even if I could remove it I don't want it removed.

**Comment by thiakil** [comment]
I see no such button.

![2017-09-10_21 02 17](https://user-images.githubusercontent.com/1788847/30249283-95c076de-966b-11e7-9f48-82676fd3b8c3.png)
![2017-09-10_21 02 27](https://user-images.githubusercontent.com/1788847/30249285-95e8debc-966b-11e7-8d4f-b4f3a8467144.png)

**Comment by thiakil** [comment]
>There is no way to move it and even if I could remove it I don't want it removed.

Also, I actually didn't say **re**move

**Comment by ZeroInputCtrl** [comment]
My bad, it's added by https://mods.curse.com/mc-mods/minecraft/248747-just-enough-buttons rather than JEI directly.
