### ISSUE TITLE
ME System causing crash

### ISSUE THREAD

**Issue by chef-boyarcheeze** [thiakil/Applied-Energistics-2#73]
With a basic ME system, 8 drives with cells inside, my game crashes anytime I am within the chunk or look generally at the location of the system. It only begins to happen after I have logged out of that world and re-entered it.

I have both Applied Llamagistics and Applied Fluidistics, and many other mods are involved as well. I was powering the system with a Mekanism Quantum Entangloporter (like the Thermal Expansion Tesseract), and getting the power from an Extreme Reactor.

- Minecraft Version: 1.12
- AE2 Version: 1.12 rv5 beta 7, currently the latest version
- Forge Version: 1.12  14.21.1.2443
[crash-2017-09-09_17.53.31-client.txt](https://github.com/thiakil/Applied-Energistics-2/files/1290165/crash-2017-09-09_17.53.31-client.txt)

**Comment by chef-boyarcheeze** [comment]
I realized I had optifine in the first crash, so I tried again without it, and it still froze and crashed.
[crash-2017-09-09_22.10.48-client.txt](https://github.com/thiakil/Applied-Energistics-2/files/1290200/crash-2017-09-09_22.10.48-client.txt)

**Comment by chef-boyarcheeze** [comment]
I found today that the actual cause of the error was that the Pam's Harvestcraft presser was messing with my thermal expansion machines. Applied Llamagistics and Applied Fluidics were most likely not the cause for the crashes.

**Comment by thiakil** [comment]
Indeed, nothing in either of those logs points to AL or AF.
