### ISSUE TITLE
Formation plane can't place block

### ISSUE THREAD

**Issue by mostlikely4r** [thiakil/Applied-Energistics-2#74]
#### Description
Using a very basic formationplane set-up the plane drops blocks as items fine but does not place the block as block.

Setup: Chest with cobblestone connected to an import bus, controller, formation pane. 

#### Environment
All the Mods 3 modpack (3.2b)

- Minecraft Version: 1.12.1
- AE2 Version: applied-llamagistics 1.12 rv5-beta-7
- Forge Version: forge-14.22.1.2478

**Comment by thiakil** [comment]
Just to rule things out, 

1. what about other blocks, like dirt?
2. is there any chunk protection in place?

**Comment by mostlikely4r** [comment]
1. I tried multiple blocks. Dirt, wood, iron ore. Same result.

2. My knowledge in this area is limited. The game is running singeplayer and this is not the spawn chunk.
In /ftb team config I 
-allowed fake players to interact with blocks
-enabled explisons 
-set the level for block editing and interaction to 'None'. 
None seemed to change the behavior. 

Are there other chunk protections systems I could check?

**Comment by thiakil** [comment]
That rules out the obvious. It's probably an oversight on my part in the 1.10 -> 1.11 change, can't remember if I tested placing blocks or not.

**Comment by mostlikely4r** [comment]
Tested, works like a charm.
