### ISSUE TITLE
Applied Lllamagistics spatial IO does not deploy correctly with Astral Sorcery installed

### ISSUE THREAD

**Issue by SingularTier** [thiakil/Applied-Energistics-2#77]
Platform:
Minecraft 1.12.1
forge-12.22.1.2485

Installed mods:
applied-llamagistics-1.12-rv5-beta-7.jar
astralsorcery-1.12-1.6.1.jar

Steps to Reproduce:

With only those 2 mods installed, whenever you try and deploy a spatial dimension, a new one is created instead.

Relevant logs:
https://pastebin.com/nPQbjSts

Also note: I cannot reproduce this with the latest Applied Energistics 1.12 version, just Llamagistics. 

https://github.com/HellFirePvP/AstralSorcery/issues/290

**Comment by thiakil** [comment]
Yup this is known, and has been fixed in dev, though looks like I haven't done a release that includes it. Shouldn't be a problem in future AS versions anyway
