### ISSUE TITLE
Adding AL disables Liahim85's mods models/textures

### ISSUE THREAD

**Issue by davqvist** [thiakil/Applied-Energistics-2#78]
#### Environment

- Minecraft Version: 1.12.1
- AL Version:  rv5-beta-7
- Forge Version: 2485

Mods from Liahim85 like Misty World are working fine until I add AL and then 80% of the textures are broken. Log says it can't read the model json anymore.
Please read https://github.com/Liahim85/Misty-World/issues/10 for details.
Liahim85 doesn't know why it is happening. Maybe you have an idea why this is happening.

**Comment by thiakil** [comment]
It seems somehow the AE2 hacky model loader is still overriding the vanilla one when those models are loaded. As far as I know it should give it back over to the standard one when not loading its model. But being a bit of a hack who knows; I'll look into making it less of a hack.

The JSON error though makes very little sense, it's bailing on the very first character... @liahim85 do your jsons contain any whitespace before the opening brace (`{`)

**Comment by Liahim85** [comment]
No. No spaces.
And they are needed?

**Comment by thiakil** [comment]
Not at all, somehow it thinks it's getting a `"` instead of a `{` from your JSON (it should never have been allowed to try to load any non-AE `ResourceLocation`s in the first place IMO)

**Comment by thiakil** [comment]
And due to Forge being a bit dumb, if a custom loader errors on `accepts`, it skips loading the model completely

**Comment by Liahim85** [comment]
I was advised here this:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3101

**Comment by thiakil** [comment]
Weird. There's probably a way to do it en masse using a linux shell and `sed` command
