### ISSUE TITLE
RF P2P Tunnel

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#8]
Any plans to re-implement RF P2P Tunnel? I think Yueh was working on a re-write of P2P but never finished it?

**Comment by thiakil** [comment]
I've added a Forge Energy tunnel instead. ;)

**Comment by Xiaminou** [comment]
Nice, what do you have to click it with to use it?

**Comment by Xiaminou** [comment]
Speaking of P2Ps, I think each type should have a craftable version, such as put a P2P Tunnel - ME in a crafting window and you get a P2P Tunnel - Fluid. So you can auto-craft them without having to click them.
I also would recommend having a config files for which items the P2P Tunnel can be clicked with to turn them into their different usages. So modpack makers can add items from mods that have been forgotten.

**Comment by thiakil** [comment]
> Nice, what do you have to click it with to use it?

Anything that has the FE capability that doesn't fall into one of the other categories.

> I think each type should have a craftable version, such as put a P2P Tunnel - ME in a crafting window and you get a P2P Tunnel - Fluid.

That would render the whole attunement system redundant, so I'm gonna say no. It can be added by pack makers / server owners / single player via the recipe files or CraftTweaker anyway. A JEI page should probably be added though.

> I also would recommend having a config files for which items the P2P Tunnel can be clicked with to turn them into their different usages. So modpack makers can add items from mods that have been forgotten.

I'll look into it. There is an Attunement API so technically anyone who finds one lacking should bother that mod's author to add a soft dependency to add it. I might just add generics for when an exact match isn't found (e.g. check for Fluid caps for Fluid Tunnel, etc)

**Comment by Xiaminou** [comment]
Hmm, I tried Thermal Dynamics' fluxducts, Mekanism's Universal Cable and Immersive Engineering's Wire Connectors, none of them turned it into an FE Tunnel. I guess that's a few that should be added.

**Comment by thiakil** [comment]
You'll likely need to use a chargeable item, those you listed would only have the capability when they're placed in the world, not as an item.

I think in my dev environment a TE Energy Cell worked.

**Comment by thiakil** [comment]
Looks like the attunement list could use some updating tho. ModIds haven't been updated in a long time.
