### ISSUE TITLE
Explosion Interaction Issues

### ISSUE THREAD

**Issue by oitsjustjose** [thiakil/Applied-Energistics-2#85]
#### Description
Well, it's a particularly interesting bug. I just finished writing a [custom explosion-based recipe handler](https://github.com/oitsjustjose/V-Tweaks/blob/1.12/src/main/java/com/oitsjustjose/vtweaks/util/MultifacetedCrafting.java) for V-Tweaks' new Enchantment, Multifaceted.

With Applied Llamagistics installed (on ForgeServ, you know the deal), the recipe doesn't work and my items just get blown up. When I disable AL and Applied Fluidics, I can craft them again no problem. I wouldn't normally report it, but then I thought about the redux of PneumaticCraft and the fact that its Compressed Iron Ingots are crafted the same way, so this wouldn't work either.

I tried finding the class responsible to pinpoint the bug, but I couldn't.... GitHub searching was a no-go, and the package structure is too vague for an outsider.

#### Environment
Entire modlist can be found on [ForgeServ's Website](http://forgeserv.net).

- Minecraft Version: 1.12.2
- AE2 Version: 1.12.1 rv5 beta 9
- Forge Version: 14.23.0.2512

**Comment by thiakil** [comment]
Bleh stupid GH didn't notify me...

There's no use of that event in either mod, so IDK what the deal is...? Does your handler fire at all?

Also, my workspace is set to 1.11, but it tells me the `ExplosionEvent ` superclass is never fired directly, only the 2 subclassess...

**Comment by oitsjustjose** [comment]
I'll have to put together a debug workspace with AL to see real quick. One sec, I'll get back to you

**Comment by oitsjustjose** [comment]
Might've just been some weird de-sync with server and client. I've resolved this by making the output item entity invulnerable.
