### ISSUE TITLE
FE Tunnel don't connect

### ISSUE THREAD

**Issue by Xiaminou** [thiakil/Applied-Energistics-2#9]
#### Description
P2P Tunnel - Forge Energy don't allow connections if they're set to the output side.

https://youtu.be/cr9q284Xoxw

as a bonus: note that when I save a P2P Tunnel into the card the tunnel goes offline until I reconnect its cable. It does that for all kind of P2P Tunnel.

#### Environment

- Minecraft Version: 1.11.2
- AE2 Version: alpha 2
- Forge Version: 2388

**Comment by thiakil** [comment]
That's not exactly how it's meant to work - the FE tunnel was copied from the RF tunnel. They're not really meant to supply a network of cables.

You need an *active pusher* sending to the *input* and something that will accept energy on the output side. Note that not everything that transports energy will support *passive* input.

I will look into letting the output sides appear connected anyway.

**Comment by Xiaminou** [comment]
Well, if they've been copied from the RF Tunnel it should be it works, because that's how I used to use them.
It's probably just a simple bug to be honest.

**Comment by thiakil** [comment]
The only difference is a visual one. It has never supported the output pulling from the input.

So, if the ducts will accept energy, they should be receiving it (provided the input it connected to an active output)

**Comment by Xiaminou** [comment]
So wait, I'm confused, are you saying it was only visual?

And yes I meant a one-way pipe-to-pipe P2P.

**Comment by thiakil** [comment]
Your bug, should only be visual. If it doesn't function, then it never will as the duct must be pulling power in that case.

**Comment by Xiaminou** [comment]
Right, guess I shouldn't assume things don't work based on visual.

**Comment by Xiaminou** [comment]
Right so I tried it:

This works:
![2017-07-11_15 48 47](https://user-images.githubusercontent.com/8670392/28071539-81a2a1b8-6650-11e7-97d1-b55ec14e4dc7.png)

But this doesn't work, which is the problem:
![2017-07-11_15 48 56](https://user-images.githubusercontent.com/8670392/28071562-914beebc-6650-11e7-9498-cec712c08c20.png)

**Comment by thiakil** [comment]
And as I said, in the 2nd image, if it does not send power, it is because the duct won't accept power from external sources. Which is how the tunnel works.
