### ISSUE TITLE
Crash using AEstuff mod 

### ISSUE THREAD

**Issue by runescapejon** [thiakil/Applied-Energistics-2#91]
when you load up AEStuff mod version 7.0.4 and place down Wireless connector it will crash you here the crash report https://pastebin.com/d3Qb2VTW
basically your missing an api from AE2 IGridHelper that class file
 
- Minecraft Version: 1.12.2
- AE2 Version: RV5-Beta-9
- Forge Version: 14.23.0.2515

**Comment by thiakil** [comment]
Basically AE2 changed their API and AE2Stuff changed accordingly. Just don't use it for now
