### ISSUE TITLE
API Incompatability with Sonar Core

### ISSUE THREAD

**Issue by Kevun1** [thiakil/Applied-Energistics-2#92]
Sonar Core, which is required for the Calculator mod and the Flux Networks mod, crashes due to the API change to IActionSource. I know there's a couple of open issues with that already, but I thought I might mention this anyway since these aren't AE2 addons but significant standalone mods. 

Here's the crash log: https://pastebin.com/vJQjpHRP

Minecraft 1.12
AL rv5 beta 10
Forge 2515

**Comment by thiakil** [comment]
Go report that to them, they should be handling that safely

**Comment by bonnedav** [comment]
Will someone please fix this?
