### ISSUE TITLE
[Suggestion] Config to remove Item Type limit for ME cells

### ISSUE THREAD

**Issue by Mohron** [thiakil/Applied-Energistics-2#99]
I tried searching if it was asked before but I couldn't find anything. Is it realistic to have a config to remove the 63 item types limit from the ME cells? This "feature" has always been my biggest beef with AE2 since it requires people to make massive numbers of smaller drives instead of a smaller collection of larger drives.

- Minecraft Version: 1.12.2
- AE2 Version: applied-llamagistics-1.12.1-rv5-beta-10
- Forge Version: forge-1.12.2-14.23.1.2560-universal

**Comment by thiakil** [comment]
It would probably require a huge change to the storage maths, which in some cases can be better than a flat number of items like RS does - e.g. a 1k storage should be able to hold more than 1000 items in certain configurations.

So it's a no for now
